apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts:
    namedCertificates:
    - names:
      - api.amaroton.pmfw2.azure.redhatworkshops.io
      servingCertificate:
        name: ocp-api