apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts:
    namedCertificates:
    - names:
        - "api.<cluster-name>.<hosted-zone-name>"
      servingCertificate:
        name: api-certs