apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ocp-ingress
  namespace: openshift-ingress
spec:
  isCA: false
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
  commonName: "apps.amaroton.bvmrc.azure.redhatworkshops.io"
  dnsNames:
  - "apps.amaroton.bvmrc.azure.redhatworkshops.io"
  - "*.apps.amaroton.bvmrc.azure.redhatworkshops.io"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: ingress-certs
