apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        azureDNS:
          clientID: 53c6af15-16e8-4866-959c-fa50f7bcdf13
          clientSecretSecretRef:
            name: azuredns-config
            key: clientSecret
          subscriptionID: 7598d218-6d54-4ed2-9f3a-533610e4e1e5
          tenantID: 64dc69e4-d083-49fc-9569-ebece1dd1408
          resourceGroupName: openenv-bvmrc
          hostedZoneName: <hosted-zone-name>
          environment: AzurePublicCloud
